Landing vue
Ratio-Belarus/landing pull request #15
Opened 2023-09-06 10:27 UTC by deadbeathd07

Лэндынг быў перапрацаваны на Vue фрэймворку, з дапамогай бiблiятэки кампанентаў Vuetify.

1. Былі дададзены яшчэ дзве лакалі - англiйская і руская. Таксама быў дададзены перамыкач мовы ў хэдэры. Па дэфолце ўсталявана беларуская мова. Пры пераключэнні мовы, ён захоўваецца ў лакальным сховішчы карыстальніка.
2. На ўсе неабходныя кнопкі была падключана форма, якая адчыняецца ў асобным акне. Былі падключаны сацыяльныя сеткі, пераход да якіх таксама аформлены ў новым акне.
3. Адпраўка формы з сайта падключана да прадстаўленага эндпоинту.
4. Дададзены мінімальны адаптыў сайта.

2023-09-09 14:21 UTC, Plistachka requested changes

2023-09-09 14:21 UTC, Plistachka commented on src/assets/twitter-icon.svg
іконку Твітара ўжо можна на гэтую замяніць: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

2023-09-09 14:21 UTC, Plistachka commented on src/store/index.js
> +          img: 'avatar.svg',
можна мне, калі ласка на гэты аватар замяніць: https://pbs.twimg.com/profile_images/1556551928678649857/fJdwL7ML_400x400.jpg

2023-09-09 14:21 UTC, Plistachka commented on src/store/index.js
> +        // {
гэтыя заглушкі можна выдаліць, яны дакладна не спатрэбяцца

2023-09-09 14:21 UTC, Plistachka commented on src/store/index.js
> +        .post('https://qa-ratio-by.herokuapp.com/contact_us', newFormFields)
`https://qa-ratio-by.herokuapp.com` трэба вынесці куды-небудзь у канфіг ці нават лепей у пераменныя асяроддзя, а тут проста клеіць да яго `/contact_us`, каб на прадакшэне можна было на іншы урл замяніць.

І кансольныя логі ніжэй таксама трэба павыдаляць

2023-09-09 14:21 UTC, Plistachka commented on package.json
> +    "build": "vite build",
каб захаваць гульню Шыбеніца, трэба каманду білда замяніць на гэтую:
```suggestion
    "build": "vite build && cp -r hangman dist/",
```

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +      "second": "the Belarusian",
`the` трэба на папярэдні радок, каб толькі на `Belarusian` быў акцэнт

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "func": "Functions",
лепей "Features"

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "connect": "Connect with us"
"Contact us"

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +      "rules": "Rules and words.",
"Grammar & Vocabulary"

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +      "second": "the Belarusian",
і першы радок лепей замяніць на "Mobile app for learning the "

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "join": "Join",
лепей "Join Us", каб даўжэй было

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "intro": "Who needs us, if not ourselves?! Definitely not your Dualingo. In October 2022, we gathered a team of volunteers and started developing a mobile application to make it easier to learn o
"Who can help us learn our native language?! Definitely not Duolingo owl..."

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "rules": "Lessons are collected by vocabulary topics: Family, Apartment, Shop, etc. Each lesson also has corresponding grammar rules.",
"Lessons are grouped by vocabulary topics"

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "prize": "Get bonuses for correctly performed exercises and daily practice without interruptions.",
Get bonuses for completing exercises and daily practice without breaks.

2023-09-09 14:21 UTC, Plistachka commented on src/locales/en.json
> +    "competition": "Every week you will be able to compete with other users of the program in terms of the number of stars received."
"Every week you will be able to compete with other users of the app in collecting the most stars."

2023-09-09 14:21 UTC, Plistachka commented on src/locales/ru.json
> +    "intro": "Кому мы нужны, если не нам самим?! Определенно не ваш Дуалинго. В октябре 2022 года мы собрали команду волонтеров и начали делать мобильное приложение, чтобы было проще выучить родной я
"Определенно не сове Дуолинго"

2023-09-09 14:21 UTC, Plistachka commented on src/components/RatioBtn.vue
у тэкста на кнопках чамусьці стаіць letter-spacing павялічаны - трэба пакінуць стандыртны спэйсінг. Таксама можна ховер крыху больш заўважны зрабіць, але гэта не крытычна

2023-09-09 14:21 UTC, Plistachka commented on src/components/RatioHeader.vue
> +          <v-list-item-title class="text-uppercase text-center" @click="chooseLang">{{
кожнаму айтэму трэба дадаць cursor: pointer, эфект на ховер і можна актыўны элемент або прыбраць са спіса, або даць яму стыль акцэнтны

2023-09-09 14:21 UTC, Plistachka commented on src/views/HomeView.vue
> +          <v-col v-for="card in functionCards" :cols="cols" class="pa-0 px-4">
іконкі трэба каб вертыкальна ўверсе былі, а не цэнтраваныя

2023-09-09 14:21 UTC, Plistachka commented on src/views/HomeView.vue
> +          <v-col v-for="(card, i) in devCards" :key="i" :cols="cols" class="col-dev">
карткі ў камандзе крыху адрозніваюцца на дызайне: больш падынг, іконкі пад тэкстам пачынаюцца, а не пад аватаркай, колер тэксту ў card.position павінен быць як у card.name, мо яшчэ што не заўважыла

2023-09-09 14:22 UTC, Plistachka commented on static/favicon.ico
фавікон можна перанесці, але трэба пакінуць і дадаць, бо зараз яго няма

2023-09-16 12:29 UTC, Plistachka commented on src/views/HomeView.vue
> +          <v-col v-for="(card, i) in devCards" :key="i" :cols="cols" class="col-dev">
зараз усё супер, толькі аватарку трэба вертыкальна не па цэнтру а зверху зрабіць

2023-09-19 08:17 UTC, deadbeathd07 commented on src/store/index.js
> +        // {
эндпаінт вынесены ў асяроддзе, дадзеныя па распрацоўшчыках - на хатнюю старонку

2023-09-19 08:18 UTC, deadbeathd07 commented on src/store/index.js
> +        .post('https://qa-ratio-by.herokuapp.com/contact_us', newFormFields)
эндпаінт вынесены ў асяроддзе, логі выдалены

2023-09-19 08:19 UTC, deadbeathd07 commented on package.json
> +    "build": "vite build",
каманду змяніла на дадзеную

2023-09-19 08:30 UTC, deadbeathd07 commented on src/views/HomeView.vue
> +          <v-col v-for="(card, i) in devCards" :key="i" :cols="cols" class="col-dev">
аватар быў зрушаны ўверх, таксама было зменена яго адлюстраванне ў няцотных картах, быў выпраўлены баг з адлюстраваннем абразкі - дададзены дадатковыя класы для правільнага выбару колеру

2023-09-21 20:19 UTC, Plistachka requested changes

2023-09-21 20:19 UTC, Plistachka commented on src/views/HomeView.vue
> +            <RatioBtn :text="$t('btn.join')" :href="ratioFormLink" />
нешта цяпер усе кнопкі "Далучыцца" па кліку нічога не робяць)

2023-09-21 20:19 UTC, Plistachka commented on src/store/index.js
> +      formFields: {
нешта я недаглядзела: трэба дадаць на іх хаця б базавую валідацыю па даўжыні і тут, і ў эндпоінце. Давай contact зробім ад 3 да 256, message ад 1 да 2048. Калі эндпоінт зваліцца на гэтай валідацыі - верне 422. У іншых выпадках, калі вярнуў не 200 - давай заўсёды паказваць паведамленне "Штосьці пайшло не так. Калі ласка, паспрабуйце пазней" (en: "Something went wrong. Please try again later"; rus: "Что-то пошло не так. Повторите позже")

2023-09-25 16:23 UTC, deadbeathd07 commented on src/store/index.js
> +      formFields: {
Дадала валідацыю палёў, а таксама апрацоўку памылак с боку сервера пры ўводзе дадзеных формы

2023-09-30 13:10 UTC, Plistachka approved these changes

2023-10-01 13:48 UTC, merged